version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo "\$CI=$CI"
      - ls -al
      - ./build.sh test
  build:
    commands:
      - npm run build
      - echo $CODEBUILD_SRC_DIR
  post_build:
    commands:
      - cd deploy
      - ./deploy.sh
artifacts:
  files:
    - '**/*'
  name: BuildArtifact
  base-directory: build
